IMAGE_NAME = "ubuntu/bionic64"
N = 3

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  (1..N).each do |i|
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.define "worker-#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
      node.vm.hostname = "worker-#{i}"
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "./worker-playbook.yml"
        ansible.extra_vars = {
          node_ip: "192.168.50.#{i + 10}",
        }
      end
    end
  end
end
